name: Development Deployment
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  deployment_of_hackathon_to_build:
    name: Deploy Build

    runs-on: ubuntu-20.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v4.1.1

      - name: Use Node.js 19
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: npm install
        run: npm install

      - name: Run create openapi Data
        run: composer run-script openapi

      - name: npm run build
        run: npm run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avz --no-o --no-g --no-perms --no-t --omit-dir-times --delete --exclude-from='.rsync-exclude'
          path: /dist
          remote_path: ${{ secrets.DEPLOY_PATH_API_BUILD }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}

      - name: Test Info Success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Successful deployment on build https://build.hackathon.exdrals.de
          webhookUrl: ${{ secrets.WEBHOOK_DISCORD_URL }}
        if: success()

      - name: Test Info Failure
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Failure deployment on build.
          webhookUrl: ${{ secrets.WEBHOOK_DISCORD_URL }}
        if: failure()
